<a href="https://colab.research.google.com/github/lcbjrrr/ML315/blob/main/ML315_2A_LinAlg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI and Machine Learning (ML)

The core difference between traditional programming and machine learning lies in how they transform inputs into outputs. In classical programming, humans explicitly write rules (code) that process raw data to produce answers. In machine learning, this process is reversed: large amounts of data together with the correct answers (labels) are fed into the system, which automatically learns and extracts the underlying rules or patterns — effectively generating a model that can then make predictions on new, unseen data without being manually programmed for every specific case. This paradigm shift enables computers to tackle complex, pattern-rich problems where writing all the rules by hand would be impractical or impossible.


![](https://pbs.twimg.com/media/G_xk3f_XAAAMW4y?format=png&name=small)

# Vectors, Arrays, and Matrices


Vectors, arrays, and matrices are fundamental data structures in Python, primarily handled using the NumPy library. A vector is a one-dimensional array of numbers, while a matrix is a two-dimensional array with rows and columns. Arrays, on the other hand, are multidimensional collections of elements, encompassing both vectors and matrices. NumPy offers efficient operations on these structures, including vectorized calculations, matrix multiplication, and linear algebra functions. This makes it a powerful tool for various applications, from data analysis to machine learning.


## numpy



NumPy arrays are more efficient and optimized for numerical computations compared to Python lists. They are homogeneous, meaning all elements must be of the same data type, while Python lists can hold elements of different types. NumPy arrays also offer vectorized operations, allowing for faster calculations on large datasets.



In [ ]:
import numpy as np
a1 = [1, 2, 3]
print(a1)
a2 = np.array([1, 2, 3])
print(a2)

[1, 2, 3]
[1 2 3]


2D matrices are a specific type of array with two dimensions: rows and columns. They are commonly used to represent tabular data or mathematical matrices. In Python, you can create and manipulate 2D matrices using both lists and NumPy arrays.

In [ ]:
b = np.array( [ [1,2,3],
                [4,5,6] ] )
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


 To access an element in a 2D array, you use two indices: one for the row and one for the column.

In [ ]:
print(b[1,1])
print(b[1][1])

5
5




## Linear Algebra



NumPy arrays x and y, adds them element-wise, and prints the resulting array z.

In [ ]:
x = np.array([1,2])
y = np.array([5,6])
z = x + y
print(z)

[6 8]


In [ ]:
x = [1,2]
y = [5,6]
z = x + y
print(z)

[1, 2, 5, 6]


Let's subtract y from x element-wise, and prints the resulting array z


In [ ]:
x = np.array([1,2])
y = np.array([5,6])
z = x - y
print(z)

[-4 -4]


Let's perform element-wise division, and prints the resulting array z.


In [ ]:
x = np.array([1,2])
y = np.array([5,6])
z = x / y
print(z)

[0.2        0.33333333]


Lastly, let's do a element-wise multiplication, and prints the resulting array z.

In [ ]:
x = np.array([[1,2],
              [3,4] ])
y = np.array([[5,6],
              [7,8]])
z = x * y
print(z)

[[ 5 12]
 [21 32]]


Matrix (dot) multiplication is a more complex operation where the elements of one matrix are multiplied by the corresponding elements of another matrix, and then the products are summed. This operation has specific rules regarding the dimensions of the matrices involved.

`z[0,0] = (1*5) + (2*7) = 19`

`z[0,1] = (1*6) + (2*8) = 22`

`z[1,0] = (3*5) + (4*7) = 43`

`z[1,1] = (3*6) + (4*8) = 50`

In [ ]:
x = np.array([[1,2],
              [3,4] ])
y = np.array([[5,6],
              [7,8]])
z = x @ y
print(z)

[[19 22]
 [43 50]]


To multiply two matrices, the number of columns in the first matrix must equal the number of rows in the second matrix.


In [ ]:
grades = np.array([ [7,8,9],
                    [5,6,7],
                    [9,9,5],
                    [9,9,9] ])
print(grades)
print(grades.shape)

[[7 8 9]
 [5 6 7]
 [9 9 5]
 [9 9 9]]
(4, 3)


In [ ]:
weights = np.array([ [0.4],
                     [0.4],
                     [0.2] ])
print(weights)
print(weights.shape)

[[0.4]
 [0.4]
 [0.2]]
(3, 1)


So...

In [ ]:
finals = grades @ weights
print(finals)

[[7.8]
 [5.8]
 [8.2]
 [9. ]]


How about the other way around?

In [ ]:
finals =  weights @ grades
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipython-input-2488955656.py in <cell line: 0>()
----> 1 finals =  weights @ grades

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

### Transposition

Transposition is the process of flipping a matrix over its diagonal interchanging rows and columns.

In [ ]:
weights_t = weights.T
print(weights_t)
print(weights_t.shape)

grades_t = grades.T
print(grades_t)
print(grades_t.shape)

print(weights_t @ grades_t)

[[0.4 0.4 0.2]]
(1, 3)
[[7 5 9]
 [8 6 9]
 [9 7 5]]
(3, 3)
[[7.8 5.8 8.2]]


### Inverted Matrix

The inverted matrix of a square matrix A is the matrix A⁻¹ that, when multiplied by A, yields the identity matrix.

In [ ]:
from numpy.linalg import inv
grades = np.array([[7, 8, 9],
                   [5, 6, 7],
                   [9, 9, 5]])
print(grades)
inv_grades = inv(grades)
print(inv_grades)
np.abs(np.round(grades @ inv_grades,0))

[[7 8 9]
 [5 6 7]
 [9 9 5]]
[[ 4.125 -5.125 -0.25 ]
 [-4.75   5.75   0.5  ]
 [ 1.125 -1.125 -0.25 ]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Basis to AI (Linear Regression)


In [ ]:
import numpy as np
X=np.array([ [1,23,1],
             [1,24,0],
             [1,31,1],
             [1,33,0],
             [1,40,1],
             [1,44,0],
             [1,55,1],
             [1,56,0],
             [1,18,1],
             [1,19,0] ])
print(X)
# X: constant, age, gender (1:male,0:female)

Y=np.array([333,320,299,280,270,250,260,255,355,345] )
print(Y)
# Insurance Premium

[[ 1 23  1]
 [ 1 24  0]
 [ 1 31  1]
 [ 1 33  0]
 [ 1 40  1]
 [ 1 44  0]
 [ 1 55  1]
 [ 1 56  0]
 [ 1 18  1]
 [ 1 19  0]]
[333 320 299 280 270 250 260 255 355 345]


We can create a predictor of the Premium (y), based on Age (x1) and Gender (x2):

$y=\beta_0+\beta_1 x_{1}+\beta_2 x_{2}$

So how do we can calculate the Beta Matrix?

$\hat{\beta}=\left(X^{\prime} X\right)^{-1} X^{\prime} Y$

In [ ]:
from numpy.linalg import inv
inv(X.T @ X) @ (X.T @ Y)

array([380.49034014,  -2.5707483 ,   8.77265306])

Let's create a function predict_premium that calculates an estimated insurance premium based on a person's age and gender. This function leverages a linear regression model, a statistical technique used to model the relationship between a dependent variable (the premium) and independent variables (age and gender).

In [ ]:
def predict_premium(age, gender):
  y = 380.49034014 +  -2.5707483*age  +   8.77265306*gender
  return y

print(predict_premium(33,1))
print(predict_premium(33,0))
print(predict_premium(35,1))